### ISSUE TITLE
Time field issue when data is sent to kinesis

### ISSUE THREAD

**Issue by sagargulabani** [aws/amazon-kinesis-streams-for-fluent-bit#83] opened 2020-10-21 07:40 UTC
Hi, our application logs output JSON, with `time` key in the following format `2020-10-21T06:23:53.835Z`. We are using the aws for fluent bit image and what ends up happening when the record is put into Kinesis is that `time` key becomes `"2020-10-21T06:23:53.835Z98896Z"`. This is our plugin configuration. That Z inbetween causes issues downstream while inserting into ES since the value is not a valid time.
```
 [OUTPUT]
        Name                kinesis
        Match               kube.*
        region              ap-south-1
        stream              test-kinesis-stream
```

**Comment by PettitWesley** [comment] 2020-10-26 08:51
What is the input for the logs? This is not really an issue with the kinesis output... 

Check out the Fluent Bit parser documentation, I am guessing that is where you timestamp is processed by Fluent Bit:  https://docs.fluentbit.io/manual/pipeline/parsers

I'm not sure how to solve this one. And I am not entirely sure what is going wrong...

> That Z inbetween causes issues downstream while inserting into ES since the value is not a valid time.

It looks like a valid time to me? And you app produces it right? Are you sure this isn't an issue with your ES configuration for parsing the timestamp (not an expert on ES, so forgive me if that is a clueless question).

The only thing I see Fluent Bit doing is increasing the precision for the timestamp, which is weird, but it doesn't seem to be adding the Z.

**Comment by sagargulabani** [comment] 2020-10-26 09:30
Hi, if you see the end part of the time, it is `53.835 Z  98896Z `, it has this extra `Z` inbetween which makes the timestamp invalid. This is indeed a problem with one of the fluentbit components and not the AWS Kinesis service.
We are using the aws for fluentbit image
eks -> fluentbit -> kubernetes filter -> kinesis output
The reason why I raised this issue here is that output from stdout fluentbit is correct.
I don't think its a problem with the kubernetes filter.

**Comment by PettitWesley** [comment] 2020-10-26 19:56
I see- can you share your full fluent bit config? And what version you are using. 

This seems to me like it might be something with the parser.

**Comment by bosatsu** [comment] 2020-10-26 20:45
Here is the full fluentbit configmap and daemonset we deploy.   There are some `##VARIABLES##` that are resolved doing deployment:

**ConfigMap**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: fluentbit
  labels:
    app.kubernetes.io/name: fluentbit
data:
  fluent-bit.conf: |
    [SERVICE]
        Parsers_File        /fluent-bit/parsers/parsers.conf
    [INPUT]
        Name                tail
        Tag                 kube.*
        Path                /var/log/containers/*.log
        DB                  /var/log/containers/log.db
        Parser              docker
        Skip_Long_Lines     Off
        Refresh_Interval    10
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Merge_Log           On
        Keep_Log            Off
        Labels              Off
        Annotations         Off
    [FILTER]
        Name                modify
        Match               kube.*
        Rename  log message
    [OUTPUT]
        Name                kinesis
        Match               kube.*
        region              ##AWS_REGION##
        stream              ##APP-STREAM##
    @INCLUDE custom.conf
    @INCLUDE systemd.conf
  systemd.conf: |
    [INPUT]
        Name                systemd
        Tag                 systemd.*
        Path                /var/log/journal
        Systemd_Filter      _SYSTEMD_UNIT=docker.service
        Systemd_Filter      _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail      true
    [OUTPUT]
        Name                kinesis
        Match               systemd.*
        region              ##AWS_REGION##
        stream              ##SYS-STREAM##
```

**Daemonset**
```
# https://aws.amazon.com/blogs/opensource/centralized-container-logging-fluent-bit/
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit
  namespace: fluentbit
---
# https://github.com/aws-samples/amazon-ecs-fluent-bit-daemon-service/blob/master/eks/eks-fluent-bit-daemonset-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: pod-log-reader
  namespace: fluentbit
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pod-log-crb
  namespace: fluentbit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-log-reader
subjects:
- kind: ServiceAccount
  name: fluentbit
  namespace: fluentbit
---
# https://github.com/aws-samples/amazon-ecs-fluent-bit-daemon-service/blob/master/eks/eks-fluent-bit-daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: fluentbit
  labels:
    app.kubernetes.io/name: fluentbit
spec:
  selector:
    matchLabels:
      name: fluentbit
  template:
    metadata:
      labels:
        name: fluentbit
    spec:
      serviceAccountName: fluentbit
      containers:
      - name: aws-for-fluent-bit
        image: amazon/aws-for-fluent-bit:2.3.1
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - name: mnt
          mountPath: /mnt
          readOnly: true
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 100Mi
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      - name: mnt
        hostPath:
          path: /mnt
```

**Comment by PettitWesley** [comment] 2020-10-27 22:15
@bosatsu This is strange... you are just using the default parser. I'm sorry, this is odd, I have not heard or seen anything like it before.

I see you are using image version 2.3.1 though- that is very old- please upgrade. Let me know if the issue persists on a newer/other versions.

One option you can try is to use the `time_key` and `time_key_format` options in the kinesis output to overwrite your existing time stamp. IIRC, if you specify the same key for the timestamp, the plugin will overwrite the existing one.

**Comment by bosatsu** [comment] 2020-10-27 23:06
Okay we will upgrade and see if that fixes this.  Quick question on the `time_key` param, is that taking the existing timestamp and reformatting?  If not, where is that time coming from, and would there be a delay between then the event happened according to the log itself vs the timestamp that kinesis would apply.

**Comment by PettitWesley** [comment] 2020-10-27 23:23
time_key will be the time that Fluent Bit assigns to the record, for which their are two cases:
- the parser parses the input timestamp from your record and uses it
- Fluent Bit creates a timestamp which will be the ingestion time

**Comment by bosatsu** [comment] 2020-10-28 18:50
We updated to the latest image, 2.8.0, and the issue still occurs.  If it helps this log is generated with [logrus](https://github.com/sirupsen/logrus)

Here is what the log looks like on the pod:

```
{"level":"info","msg":"asynchronously updating key : 253344 for cache white_list","time":"2020-10-28T17:52:51Z"}
```

Here is what it looks like coming out of kinesis:
```
{
    "aws_region": "us-west-2",
    "cloud": {
        "provider": "aws",
        "region": "us-west-2"
    },
    "ecs": {
        "version": "1.5.0"
    },
    "event": {
        "kind": "event"
    },
    "event_source": "aws:kinesis",
    "host": {
        "name": "169.254.125.93"
    },
    "kubernetes": {
        "container_hash": "538333841962.dkr.ecr.us-west-2.amazonaws.com/domain-iq-cache@sha256:4c465327431d6171cd3f2af1cda0f131c8397312f93bf06a1f13b9cf7580c140",
        "container_image": "538333841962.dkr.ecr.us-west-2.amazonaws.com/domain-iq-cache:master-cc6b4b6a",
        "container_name": "domain-iq-cache",
        "docker_id": "e1db2b71a5d51420e2c1245605cb5c4c51099f851d3da8ad85ec3ba89a249a7f",
        "host": "ip-10-114-91-184.us-west-2.compute.internal",
        "namespace_name": "default",
        "pod_id": "e5685e7a-3f43-4966-bfe1-3da3fac424cb",
        "pod_name": "domain-iq-cache-586454ffc-95qrr"
    },
    "level": "info",
    "message": "{\"kubernetes\":{\"container_hash\":\"538333841962.dkr.ecr.us-west-2.amazonaws.com/domain-iq-cache@sha256:4c465327431d6171cd3f2af1cda0f131c8397312f93bf06a1f13b9cf7580c140\",\"container_image\":\"538333841962.dkr.ecr.us-west-2.amazonaws.com/domain-iq-cache:master-cc6b4b6a\",\"container_name\":\"domain-iq-cache\",\"docker_id\":\"e1db2b71a5d51420e2c1245605cb5c4c51099f851d3da8ad85ec3ba89a249a7f\",\"host\":\"ip-10-114-91-184.us-west-2.compute.internal\",\"namespace_name\":\"default\",\"pod_id\":\"e5685e7a-3f43-4966-bfe1-3da3fac424cb\",\"pod_name\":\"domain-iq-cache-586454ffc-95qrr\"},\"level\":\"info\",\"msg\":\"asynchronously updating key : 253344 for cache white_list\",\"stream\":\"stdout\",\"time\":\"2020-10-28T17:52:51Z472795444Z\"}",
    "msg": "asynchronously updating key : 253344 for cache white_list",
    "stream": "stdout",
    "time": "2020-10-28T17:52:51Z472795444Z"
}
```

**Comment by sagargulabani** [comment] 2020-10-30 06:31
I performed the same test  using version 2.8.0 for my service and I did run into the same issue. 
I did apply the stdout output plugin to the same log entry besides Kinesis, all data passing through the same filters. 
The stdout contains the timestamp in a valid format, while the kinesis does not.

**Comment by PettitWesley** [comment] 2020-10-30 08:15
> The stdout contains the timestamp in a valid format, while the kinesis does not.

This is super weird, because unless I am mistaken, from the point of view of the kinesis plugin that time field is just an opaque string.

I'm in the middle of trying to work on a new release right now... but I have added "try to repro this thing" on my todo list for when I have time.

In the meantime, can you try try the time_key and time_key_format workaround that I suggested and see if the results are satisfactory?

**Comment by bosatsu** [comment] 2020-11-02 16:57
We tried the time_key and that does work as a workaround, though the is obviously slightly off.   Will look forward to seeing what you find as you move through the new release.

**Comment by PettitWesley** [comment] 2020-11-10 01:40
Hey guys... I have not forgotten about this issue. I have made some progress.

I built a simple container which just continually spits out the example log message you gave me. I then deployed it to a k8s cluster and ran Fluent Bit with a config similar to the one you are using.

Findings:
1. I can reproduce the issue with the Kinesis Plugin.
2. I can also reproduce the issue with the CloudWatch Logs Go Plugin.
3. I can't reproduce it with the new CloudWatch Logs Core/C plugin.

I also can't reproduce it outside of k8s in an environment where the logs aren't being parsed as JSON. 

So my suspicion is that when Fluent Bit parses that timestamp, it changes it to some internal type, which is then passed to the Go Plugins in such a way that they do this weird manipulation to it. I think its a bug in the Golang Fluent Bit interface.

**Comment by PettitWesley** [comment] 2020-11-16 23:52
Back on this today, I can repro it with the go stdout example, so this is clearly something in the go framework: https://github.com/fluent/fluent-bit-go/tree/master/examples/out_gstdout

I am struggling to come up with a config/scenario that reproduces this issue outside of Kubernetes. This was making it very inconvenient to debug until I realized that I could build/write code on one of the nodes in my testing cluster.

**Comment by PettitWesley** [comment] 2020-11-17 01:26
Small finding- the fact that your app outputs the timestamp to a key called `time` is important.

I changed my app to log this:
```
{
    "level":"info",
    "msg":"asynchronously updating key : 253344 for cache white_list",
    "some-non-time-key":"2020-10-28T17:52:51Z",
    "time":"2020-10-28T17:52:51Z",
    "date":"2020-10-28T17:52:51Z"
}
```

And the output I get is:
```
{
  "some-non-time-key": "2020-10-28T17:52:51Z",
  "date": "2020-10-28T17:52:51Z",
  "stream": "stdout",
  "time": "2020-10-28T17:52:51Z196020184Z",
  "level": "info",
  "msg": "asynchronously updating key : 253344 for cache white_list"
}
```

The timestamp is only screwed up for the one field named `time`. Thus, I suspect that the Kubernetes filter is parsing your time key as a time stamp, and internally converting it to a msgpack time value. The Go plugin framework is then weirdly processing the msgpack time value. That's my current theory.

This code suggests that a msgpack time value is converted into a `time.Time` in Go: https://github.com/ugorji/go/blob/master/codec/msgpack.go#L948

The next step is to try to figure out what type the Go plugin framework sees this value as. May be its something in json marshalling? 

Unfortunately this issue is not my highest priority right now, so I might not return to this till next week.

**Comment by bosatsu** [comment] 2020-11-17 02:38
Thank you for continuing to dig into this, really appreciate it.  I'm on vacation this week, but will review when I get back.

**Comment by PettitWesley** [comment] 2020-11-18 01:28
@bosatsu Yeah so the finding is that it seems if you could change the name of your time stamp field (or may be change your parser instead), then this would go away.

**Comment by zhonghui12** [comment] 2021-05-07 00:21
This issue will be closed as there is no further discussion on it. Please reopen it if you have more questions.

**Closed as completed by zhonghui12** 2021-05-07 00:21 UTC

**Comment by jpage-godaddy** [comment] 2024-03-25 20:30
This is still an issue; @PettitWesley is this something you can reopen?
